strategy_executor.py: TypeError Fixes, examples.
                    Error: Invalid value '0.15255000000000002' for dtype 'int64' <class 'TypeError'>
                    Error: Invalid value '2026-03-01 13:55:00.123456' for dtype 'str'. Value should be a string or missing value, got 'datetime' instead. <class 'TypeError'> Invalid value
Seems these TypeError's depends on python/pandas versions.